import Header from "./components/Header";

export const metadata = {
    title: "ClosedTable",
    description: "Generated by create next app",
};

export default function layout({
    children,
    params: { slug },
}: {
    children: React.ReactNode;
    params: { slug: string };
}) {
    return (
        <main className="max-w-screen-2xl m-auto bg-white">
            <Header name={slug} />
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                {children}
            </div>
        </main>
    );
}

// WEWTDD7BzENee0na
